data "azurerm_kubernetes_cluster" "this" {
  name                = var.cluster_name
  resource_group_name = var.resource_group_name
}

locals {
  app_namespace = "{{ cookiecutter.project_slug }}"
}

# Connection URIs generated by the CNPG clusters deployed via gitops
data "kubernetes_secret" "pg_app" {
  metadata {
    name      = "pg-app-cluster-app"
    namespace = local.app_namespace
  }
}

data "kubernetes_secret" "pg_vectors" {
  metadata {
    name      = "pg-vectors-cluster-app"
    namespace = local.app_namespace
  }
}

data "kubernetes_secret" "pg_checkpoints" {
  metadata {
    name      = "pg-checkpoints-cluster-app"
    namespace = local.app_namespace
  }
}

resource "vault_mount" "secret" {
  path    = "secret"
  type    = "kv"
  options = { version = "2" }
}

resource "vault_policy" "app_read" {
  name = "{{ cookiecutter.project_slug }}-read"

  policy = <<-EOT
    path "secret/data/app_secrets" {
      capabilities = ["read"]
    }
  EOT
}

# Kubernetes auth: the app logs in with its projected ServiceAccount token;
# Vault validates it via the TokenReview API using its own service account
# (the chart's default authDelegator binding).
resource "vault_auth_backend" "kubernetes" {
  type = "kubernetes"
}

resource "vault_kubernetes_auth_backend_config" "this" {
  backend         = vault_auth_backend.kubernetes.path
  kubernetes_host = "https://kubernetes.default.svc"
}

resource "vault_kubernetes_auth_backend_role" "app" {
  backend                          = vault_auth_backend.kubernetes.path
  role_name                        = "{{ cookiecutter.project_slug }}"
  bound_service_account_names      = ["{{ cookiecutter.project_slug }}"]
  bound_service_account_namespaces = [local.app_namespace]
  token_policies                   = [vault_policy.app_read.name]
  token_ttl                        = 3600
}

# Pull secret for the private GHCR image referenced by the app Deployment
resource "kubernetes_secret_v1" "ghcr_pull" {
  metadata {
    name      = "ghcr-pull"
    namespace = local.app_namespace
  }

  type = "kubernetes.io/dockerconfigjson"

  data = {
    ".dockerconfigjson" = jsonencode({
      auths = {
        "ghcr.io" = {
          username = var.github_user
          password = var.github_pat
          auth     = base64encode("${var.github_user}:${var.github_pat}")
        }
      }
    })
  }
}

# Full payload required by agent_lab's VaultConfigSource; every key must be
# present or config loading raises KeyError at startup.
resource "vault_kv_secret_v2" "app_secrets" {
  mount = vault_mount.secret.path
  name  = "app_secrets"

  data_json = jsonencode({
    api_base_url       = var.api_base_url
    cdp_url            = ""
    auth_enabled       = false
    auth_url           = ""
    auth_realm         = ""
    auth_client_id     = ""
    auth_client_secret = ""
    broker_url         = "redis://redis.${local.app_namespace}.svc.cluster.local:6379/0"
    db_url             = data.kubernetes_secret.pg_app.data["uri"]
    db_vectors         = data.kubernetes_secret.pg_vectors.data["uri"]
    db_checkpoints     = data.kubernetes_secret.pg_checkpoints.data["uri"]
  })
}
