data "azurerm_kubernetes_cluster" "this" {
  name                = var.cluster_name
  resource_group_name = var.resource_group_name
}

locals {
  app_namespace = "{{ cookiecutter.project_slug }}"
}

data "azurerm_key_vault" "unseal" {
  name                = var.unseal_key_vault_name
  resource_group_name = var.resource_group_name
}

# One-time Vault initialization. Vault comes up sealed and reports NotReady
# until `operator init` runs once; auto-unseal (the azurekeyvault seal wired in
# 02_gitops) then handles every restart. This waits for the Vault endpoint,
# initializes over the public ingress, and stores the root token + recovery
# keys in the unseal Key Vault. Idempotent: an already-initialized Vault is
# left untouched. Runs before the vault provider is configured, via the
# depends_on on the secret read below.
resource "terraform_data" "vault_init" {
  triggers_replace = {
    vault_hostname = var.vault_hostname
    key_vault_name = var.unseal_key_vault_name
    secret_name    = var.init_secret_name
  }

  provisioner "local-exec" {
    interpreter = ["/bin/sh", "-c"]

    environment = {
      VAULT_ADDR  = "https://${var.vault_hostname}"
      KEY_VAULT   = var.unseal_key_vault_name
      SECRET_NAME = var.init_secret_name
    }

    command = <<-EOT
      set -eu

      echo "waiting for vault endpoint at $VAULT_ADDR ..."
      code=000
      for i in $(seq 1 60); do
        code=$(curl -sk -o /dev/null -w '%%{http_code}' "$VAULT_ADDR/v1/sys/health" || echo 000)
        [ "$code" != "000" ] && break
        echo "  ($i/60) no response yet..."
        sleep 5
      done
      if [ "$code" = "000" ]; then
        echo "vault did not respond at $VAULT_ADDR after 5m" >&2
        exit 1
      fi

      initialized=$(curl -sk "$VAULT_ADDR/v1/sys/init" | jq -r '.initialized')
      if [ "$initialized" = "true" ]; then
        echo "vault already initialized; leaving stored init payload untouched."
        exit 0
      fi

      echo "initializing vault (auto-unseal via azurekeyvault seal)..."
      init_json=$(curl -sk -X POST \
        -d '{"recovery_shares":1,"recovery_threshold":1}' \
        "$VAULT_ADDR/v1/sys/init")

      root_token=$(printf '%s' "$init_json" | jq -r '.root_token // empty')
      if [ -z "$root_token" ]; then
        echo "init failed: $init_json" >&2
        exit 1
      fi

      echo "storing init payload in key vault '$KEY_VAULT' secret '$SECRET_NAME'..."
      az keyvault secret set \
        --vault-name "$KEY_VAULT" \
        --name "$SECRET_NAME" \
        --value "$init_json" \
        --output none

      echo "vault initialized and auto-unsealed; root token stored in key vault."
    EOT
  }
}

# Root token produced by vault_init above; consumed by the vault provider.
# The depends_on defers this read until after init has written the secret, so
# a single apply both initializes and configures Vault.
data "azurerm_key_vault_secret" "vault_init" {
  name         = var.init_secret_name
  key_vault_id = data.azurerm_key_vault.unseal.id

  depends_on = [terraform_data.vault_init]
}

# The CNPG clusters provision their secrets asynchronously after 02_gitops.
# Block here until they exist so the data sources below never read too early.
resource "terraform_data" "gitops_converged" {
  provisioner "local-exec" {
    interpreter = ["/bin/sh", "-c"]

    environment = {
      RG      = var.resource_group_name
      CLUSTER = var.cluster_name
      NS      = local.app_namespace
    }

    command = <<-EOT
      set -eu
      KUBECONFIG_FILE=$(mktemp)
      trap 'rm -f "$KUBECONFIG_FILE"' EXIT
      az aks get-credentials --resource-group "$RG" --name "$CLUSTER" \
        --admin --overwrite-existing --file "$KUBECONFIG_FILE" --output none

      has_secret() {
        kubectl --kubeconfig "$KUBECONFIG_FILE" get secret "$2" -n "$1" >/dev/null 2>&1
      }

      echo "waiting for gitops-provisioned secrets (postgres app/vectors/checkpoints)..."
      for i in $(seq 1 60); do
        if has_secret "$NS" pg-app-cluster-app \
          && has_secret "$NS" pg-vectors-cluster-app \
          && has_secret "$NS" pg-checkpoints-cluster-app; then
          echo "all required secrets present."
          exit 0
        fi
        echo "  ($i/60) not all secrets present yet..."
        sleep 10
      done
      echo "required secrets did not appear after 10m" >&2
      exit 1
    EOT
  }
}

# Connection URIs generated by the CNPG clusters deployed via gitops
data "kubernetes_secret" "pg_app" {
  metadata {
    name      = "pg-app-cluster-app"
    namespace = local.app_namespace
  }

  depends_on = [terraform_data.gitops_converged]
}

data "kubernetes_secret" "pg_vectors" {
  metadata {
    name      = "pg-vectors-cluster-app"
    namespace = local.app_namespace
  }

  depends_on = [terraform_data.gitops_converged]
}

data "kubernetes_secret" "pg_checkpoints" {
  metadata {
    name      = "pg-checkpoints-cluster-app"
    namespace = local.app_namespace
  }

  depends_on = [terraform_data.gitops_converged]
}

resource "vault_mount" "secret" {
  path    = "secret"
  type    = "kv"
  options = { version = "2" }
}

resource "vault_policy" "app_read" {
  name = "{{ cookiecutter.project_slug }}-read"

  policy = <<-EOT
    path "secret/data/app_secrets" {
      capabilities = ["read"]
    }
  EOT
}

# Kubernetes auth: the app logs in with its projected ServiceAccount token;
# Vault validates it via the TokenReview API using its own service account
# (the chart's default authDelegator binding).
resource "vault_auth_backend" "kubernetes" {
  type = "kubernetes"
}

resource "vault_kubernetes_auth_backend_config" "this" {
  backend         = vault_auth_backend.kubernetes.path
  kubernetes_host = "https://kubernetes.default.svc"
}

resource "vault_kubernetes_auth_backend_role" "app" {
  backend                          = vault_auth_backend.kubernetes.path
  role_name                        = "{{ cookiecutter.project_slug }}"
  bound_service_account_names      = ["{{ cookiecutter.project_slug }}"]
  bound_service_account_namespaces = [local.app_namespace]
  token_policies                   = [vault_policy.app_read.name]
  token_ttl                        = 3600
}

# Pull secret for the private GHCR image referenced by the app Deployment
resource "kubernetes_secret_v1" "ghcr_pull" {
  metadata {
    name      = "ghcr-pull"
    namespace = local.app_namespace
  }

  type = "kubernetes.io/dockerconfigjson"

  data = {
    ".dockerconfigjson" = jsonencode({
      auths = {
        "ghcr.io" = {
          username = var.github_user
          password = var.github_pat
          auth     = base64encode("${var.github_user}:${var.github_pat}")
        }
      }
    })
  }
}

# Full payload required by agent_lab's VaultConfigSource; every key must be
# present or config loading raises KeyError at startup.
resource "vault_kv_secret_v2" "app_secrets" {
  mount = vault_mount.secret.path
  name  = "app_secrets"

  data_json = jsonencode({
    api_base_url       = "https://${var.app_hostname}"
    cdp_url            = "http://cdp.${local.app_namespace}.svc.cluster.local:9222"
{%- if cookiecutter.auth_enabled %}
    auth_enabled       = true
    auth_url           = var.auth_url
    auth_realm         = var.auth_realm
    auth_client_id     = var.auth_client_id
    auth_client_secret = var.auth_client_secret
{%- else %}
    auth_enabled       = false
    auth_url           = ""
    auth_realm         = ""
    auth_client_id     = ""
    auth_client_secret = ""
{%- endif %}
    broker_url         = "redis://redis.${local.app_namespace}.svc.cluster.local:6379/0"
    db_url             = data.kubernetes_secret.pg_app.data["uri"]
    db_vectors         = data.kubernetes_secret.pg_vectors.data["uri"]
    db_checkpoints     = data.kubernetes_secret.pg_checkpoints.data["uri"]
  })
}
