api_base_url: "http://test"
db:
  url: "sqlite:///./agent_lab.db"
  vectors: "postgresql://postgres:postgres@localhost:15432/agent_lab_vectors"
  checkpoints: "postgresql://postgres:postgres@localhost:15432/agent_lab_checkpoints"
vault:
  url: "http://localhost:18200"
  token: "dev-only-token"
