db:
  url: "postgresql://postgres:postgres@localhost:5432/agent_lab"
  checkpoints: "postgresql://postgres:postgres@localhost:5432/agent_lab_checkpoints"
vault:
  url: "http://localhost:8200"
  token: "dev-only-token"
