db:
  url: "postgresql://postgres:postgres@localhost:5432/agent_lab"
  checkpoints: "postgresql://postgres:postgres@localhost:5432/agent_lab_checkpoints"
vault:
  url: "http://localhost:8200"
  token: "dev-only-token"
tracer:
  service_name: "agent-lab-app"
  collector_endpoint: "http://localhost:4318"
