version: '3.8'
services:
  app:
    build: .
    networks:
      - agent-lab
    volumes:
      - .:/app
    ports:
      - "18000:8000"
    environment:
      DOCKER: 1
    depends_on:
      postgres-setup:
        condition: service_completed_successfully

  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    networks:
      - agent-lab
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-setup:
    image: pgvector/pgvector:pg16
    networks:
      - agent-lab
    environment:
      PGPASSWORD: postgres
    command: >
      bash -c '
        echo "CREATE DATABASE agent_lab;" | psql -h postgres -U postgres
      '
    depends_on:
      postgres:
        condition: service_healthy

  vault:
    image: hashicorp/vault:1.18
    ports:
      - "8200:8200"
    networks:
      - agent-lab
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "dev-only-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev

networks:
  agent-lab:
    name: agent-lab
