version: '3.8'
services:
  app:
    build: .
    networks:
      - agent-lab
    volumes:
      - .:/app
    ports:
      - "18000:8000"
    environment:
      DOCKER: 1
    depends_on:
      postgres-setup:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    networks:
      - agent-lab
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    networks:
      - agent-lab
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-setup:
    image: pgvector/pgvector:pg16
    networks:
      - agent-lab
    environment:
      PGPASSWORD: postgres
    command: >
      bash -c '
        echo "CREATE DATABASE agent_lab;" | psql -h postgres -U postgres
      '
    depends_on:
      postgres:
        condition: service_healthy

  vault:
    image: vault:1.18.1
    ports:
      - "8200:8200"
    networks:
      - agent-lab
#    volumes:
#      - ./volumes/logs:/vault/logs
#      - ./volumes/file:/vault/file
#      - ./volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json

#  opensearch:
#    image: opensearchproject/opensearch:latest
#    networks:
#      - agent-lab
#    ports:
#      - "9200:9200"
#      - "9600:9600"
#    environment:
#      - "cluster.name=opensearch-cluster"
#      - "discovery.type=single-node"
#      - "bootstrap.memory_lock=true"
#      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "DISABLE_SECURITY_PLUGIN=true"
#      - "DISABLE_INSTALL_DEMO_CONFIG=true"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    #volumes:
#    #  - ./opensearch-data:/usr/share/opensearch/data
#
#  opensearch-dashboards:
#    image: opensearchproject/opensearch-dashboards:latest
#    networks:
#      - agent-lab
#    ports:
#      - 5601:5601
#    environment:
#      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
#      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"

networks:
  agent-lab:
    name: agent-lab
