replicaCount: 1

secretName: agent-lab-secret

image:
  repository: bsantanna/agent-lab
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

nameOverride: ""

fullnameOverride: ""

config:
  OLLAMA_ENDPOINT: "http://moon.btech.software:11434"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 8000

podAnnotations: { }

podLabels: { }

podSecurityContext: { }

securityContext: { }

ingress:
  enabled: true
  className: "nginx"
  annotations:
     kubernetes.io/ingress.class: nginx
    # cert-manager.io/issuer: "letsencrypt-prod"
  hosts:
    - host: agentlab.btech.software
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName:agent-lab-tls
  #    hosts:
  #      - agentlab.btech.software

resources: {}

livenessProbe:
  httpGet:
    path: /status/liveness
    port: http
readinessProbe:
  httpGet:
    path: /status/readiness
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
