apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ cookiecutter.project_slug }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - secretName: {{ cookiecutter.project_slug }}-tls
      hosts:
        - ${app_hostname}
  rules:
    - host: ${app_hostname}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ cookiecutter.project_slug }}
                port:
                  number: 80
