/**
 * Agent-Lab
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {AgentSetting} from './agentSetting';


export interface AgentExpanded {
  id: string;
  is_active: boolean;
  created_at: string;
  agent_name: string;
  agent_type: string;
  agent_summary: string;
  language_model_id: string;
  ag_settings?: Array<AgentSetting> | null;
}
