/**
 * Agent-Lab
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgentCreateRequest {
  agent_name: string;
  agent_type: string;
  language_model_id: string;
}
