/**
 * Agent-Lab
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Agent {
  id: string;
  is_active: boolean;
  created_at: string;
  agent_name: string;
  agent_type: string;
  agent_summary: string;
  language_model_id: string;
}
