/**
 * Agent-Lab
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Attachment {
  id: string;
  is_active: boolean;
  created_at: string;
  file_name: string;
  parsed_content: string;
  embeddings_collection: string | null;
}
