/**
 * Agent-Lab
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {LanguageModelSetting} from './languageModelSetting';


export interface LanguageModelExpanded {
  id: string;
  created_at: string;
  is_active: boolean;
  language_model_tag: string;
  integration_id: string;
  lm_settings?: Array<LanguageModelSetting> | null;
}
