/**
 * Agent-Lab
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LanguageModelSettingUpdateRequest {
  language_model_id: string;
  setting_key: string;
  setting_value: string;
}
