/**
 * Agent-Lab
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MessageRequest {
  message_role: string;
  message_content: string;
  agent_id: string;
  attachment_id?: string | null;
}
