/**
 * Agent-Lab
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Message} from './message';
import {Attachment} from './attachment';


export interface MessageExpanded {
  message_role: string;
  message_content: string;
  agent_id: string;
  id?: string | null;
  is_active?: boolean | null;
  created_at?: string | null;
  response_data?: { [key: string]: any; } | null;
  replies_to: Message | null;
  attachment: Attachment | null;
}
